export const NOW_LIVE_ROLE_UPDATER = "NOW_LIVE_ROLE_UPDATER"
export const REMOVE_NEW_ROLE = "REMOVE_NEW_ROLE"
export const AUTO_WEEK_END = "AUTO_WEEK_END"
export const REFRESH_SUPPORT_TIERS = "REFRESH_SUPPORT_TIERS"