# Generic Errors
no_user_error: ❌ You have not been added to the database- please contact a member of the <@&880214274327318588>
no_user_error_third_person: ❌ They have not been added to the database.
no_user_error_third_person_several: ❌ Someone has not been added to the database.
no_user_url_error: ❌ Their Twitch username has not been added to the database.
no_user_url_error_1st_person: ❌ Your Twitch username has not been added to the database. Please use the $link command to add it.

# Generic Warnings
no_permission: ⚠️ You are not permitted to use this command.
invalid_content_length: ⚠️ Your command does not have enough arguments.
invalid_url: ⚠️ That is not a url!
no_user: ⚠️ The specified member does not exist!
cant_send_dm: ⚠️ The bot was unable to send you a DM, do you have DMs from this server disabled?

# Specific Warnings
not_a_number: ⚠️ The points awarded is not a number!
not_a_number_tags: ⚠️ The tags stated is not a number!
not_a_number_weeks: ⚠️ The weeks given is not a number!
not_a_stage: ⚠️ Stages range between 0 and 3.
no_event_history: ⚠️ The specified user has never participated in a event!
should_not_be_a_url: ⚠️ Please do not enter your Twitch URL but instead your Twitch username
event_history_invalid_type: ⚠️ The second argument should either be "attendance" or "evented"
not_eligible_for_on_leave: ⚠️ You are not eligible to go on leave
not_a_number_slot: ⚠️ The slot provided is not a number!
not_a_slot: ⚠️ The slot provided does not exist!
not_calendar_eligible: ⚠️ The member is not calendar eligible. Add "force" as a third argument to the command to override this warning.
bad_username_to_url: ⚠️ Please change your Discord username so it contains your Twitch username.
calendar_slot_taken: ⚠️ The slot specified is already taken. Add "force" as a third argument to the command to override this warning.
not_a_event_train: ⚠️ The event train specified isn't a real name.
not_a_table: ⚠️ No table in the database goes under that name.
no_onleave_record: ⚠️ The specified member has never been On Leave!

# Success Messages
manual_user_addition: ✅ The specified user and their Twitch url are now inside of the database.
manual_url_addition: ✅ The specified user now has their twitch url attached to the database.
added_event: ✅ The event has now been added for the specified user(s).
point_change: ✅ The member(s) points were changed
event_participation_removal: ✅ The specified user has no longer participated in the event.
purge: ✅ All event and support tags from 4 weeks ago have been purged.
person_visited: ✅ The specified streamer has been logged as evented.
on_leave_roles_purged: ✅ All members who have been On Leave for over a month have had the role revoked. Please remember to remove their role reactions.
lock_calendar: 🔒 The calendar channel is now locked, and therefore messages can now be deleted safely.
unlock_calendar: 🔓 The calendar channel is now unlocked, meaning that deleting calendar tags will now affect the database.
lock_request_a_slot: 🔒 The bot will now ignore Request A Slot
unlock_request_a_slot: 🔓 The bot will now read Request A Slot
new_calendar: ✅ A new calendar has been started!
added_to_calendar: ✅ The specified member has been added to the calendar.
deleted_slot: ✅ The slot has now been cleared.
added_comment: ✅ The comment has been added.
added_tags: ✅ The tags were added.
changed_stage: ✅ The member's stage was changed.
event_goto_confirmation: ✅ A message has been posted in
onleave_forgiven: ✅ The member's On Leave record has been forgiven.

# Specific Messages
never_been_evented: ❗ The specified user has never been evented in or out of community!
slot_not_taken: ❗ The slot is already free!
shutdown: ❗ The bot has been shut down.
restart: ❗ The bot has restarted.
no_attendance: ❗ No event attendance was taken.
event_message: |
  <@&880214274297974868> DING! DING! it's Nearly event TIME! The **%** event Train is taking off in 20 minutes!
  Come to event Voice Chat, 10 mins before the event starts and let's make this event Train EPIC!

  event Rules:
  •  NO Cursing or self-promo in the event Voice Channel
  •  NO Negativity or personal remarks towards community members
  •  NO Streaming while you're eventing
  •  NO talking in other discord channels
  •  events last 30 mins, up to an hour
  •  We will be dropping links in the event-links channel every 5 mins
  •  event attendance is taken at the end of each 30-minute event
  •  Push to talk is on but you are not required to talk or have a mic
  •  You do not have to follow, sub or donate bits to any streamers 

# Activity Check Messages
stage_1: ❗ You failed last week's activity requirements. If you fail again next week, your level will be reset.
stage_2: ❗ You failed last week's activity requirements. If you fail again next week, your membership will be terminated.
stage_3: ❗ You failed last week's activity requirements. Because of this, you may be kicked from the server.